language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - flex
      - bison
      - cmake
before_script:
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

script: make && make test
